logs:
  # (Required) Path to logs file (default: $CWD/job-worker.log)
  path: $CWD\job-worker.log
  # (Optional) Log level. Choices: [DEBUG, INFO, WARNING, ERROR] (default: INFO)
  level: INFO
  # (Optional) Log anything related to watcher (default: false)
  log_watcher: false
  # (Optional) Log anything related to worker (default: true)
  log_worker: true
jobs:
  # (Required) Task name
- name: example
  # (Optional) Upload directory. Must be absolute. Overrides global `upload_dir`
  upload_dir: null
  # (Optional) Output directory. Must be absolute. Overrides global `output_dir`
  output_dir: null
  # (Optional) Temporary directory. Must be absolute. Overrides global `tmp_dir`
  tmp_dir: null
  # (Required) Commands to run. Can be a `string`, `Command`, or list of `strings` or `Commands`
  cmd:
    # (Required) CLI command
  - value: 'echo Working on: {{ name }}'
    # (Optional) Regex to extract input data and use in command. Works after global `extract`
    extract: null
    # (Optional) Skip file if no match found (default: true)
    skip_no_match: true
    # (Optional) Continue on command failure. Overrides global `continue_on_error` (default: false)
    continue_on_error: true
    # (Optional) Show error in logs. Does not apply if `continue_on_error` is false (default: true)
    show_error: true
    # (Optional) Variables to pass to command (default: null)
    vars: null
  - 'echo File extension: {{ input_ext }}'
  # (Optional) Regex to extract input data and use in commands. Use (?P<name>...) to named groups
  extract: (?P<name>.*\..{2,})$
  # (Optional) Skip file if no match found (default: true)
  skip_no_match: true
  # (Optional) Maximum number of iterations. Overrides global `max_iterations`
  max_iterations: null
  # (Optional) Scan interval. Overrides global `scan_interval`
  scan_interval: null
  # (Optional) Scan exclude. Allows RegEx. Exclude > Include (default: [])
  scan_exclude: []
  # (Optional) Scan include. Allows RegEx. Exclude > Include (default: [])
  scan_include: []
  # (Optional) Include directories. Overrides global `include_dirs`
  include_dirs: null
  # (Optional) Variables to pass to command (Default: null)
  vars: null
# (Optional) Maximum number of iterations per file. 0 for infinite (default: 1)
max_iterations: 1
# (Optional) Scan interval (default: 15 seconds)
scan_interval: 15
# (Optional) Include directories (default: false)
include_dirs: false
# (Required) Upload directory. Must be absolute (default: $CWD/upload)
upload_dir: ./app/upload
# (Optional) Temporary directory. Must be absolute (default: $CWD/tmp)
tmp_dir: /app/tmp
# (Required) Output directory. Must be absolute (default: $CWD/output)
output_dir: /app/output
# (Optional) Continue on command failure (default: false)
continue_on_error: false
# (Optional) Use persistent or in-memory database (default: false)
db_persistent: false
# (Optional) Search recursively (default: true)
recursive: true
